# Generated by Django 5.2.15 on 2026-06-23 18:16

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('zone', models.CharField(max_length=120, verbose_name='Zona')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Punto geográfico en formato longitud, latitud.', srid=4326, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(verbose_name='Fecha y hora de medición')),
                ('pm25', models.FloatField(help_text='Concentración en µg/m³.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='PM2.5')),
                ('co', models.FloatField(help_text='Concentración en ppm.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO')),
                ('o3', models.FloatField(help_text='Concentración en ppb.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='O₃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='air_quality.station', verbose_name='Estación')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.CharField(choices=[('PM25', 'PM2.5'), ('CO', 'CO'), ('O3', 'O₃')], max_length=10, verbose_name='Contaminante')),
                ('level', models.CharField(choices=[('MODERATE', 'Moderada'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=15, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='air_quality.measurement', verbose_name='Medición')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='alert_active_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['station', '-recorded_at'], name='measurement_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['-recorded_at'], name='measurement_recorded_time_idx'),
        ),
    ]
