# Generated by Django 5.2.16 on 2026-07-09 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='aqi_us',
            field=models.IntegerField(blank=True, null=True, verbose_name='AQI US'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='main_pollutant',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contaminante principal'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source',
            field=models.CharField(choices=[('SIMULATED', 'Simulado'), ('IQAIR', 'IQAir')], default='SIMULATED', max_length=20, verbose_name='Fuente de datos'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ciudad fuente'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuesta original de la API'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='co',
            field=models.FloatField(blank=True, help_text='Concentración en ppm.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CO'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='o3',
            field=models.FloatField(blank=True, help_text='Concentración en ppb.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='O₃'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pm25',
            field=models.FloatField(blank=True, help_text='Concentración en µg/m³.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PM2.5'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['source', '-recorded_at'], name='measurement_source_time_idx'),
        ),
    ]
